# Generated by Django 4.1.4 on 2022-12-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0003_alter_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'ADULT'), ('2', 'KID')], default='ADULT', max_length=191, null=True),
        ),
    ]
